---

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform-build-user"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform-post-packer"
    schedule:
      interval: "weekly"
