---
- name: Install BloodHound and BloodHound.py
  ansible.builtin.package:
    name:
      - bloodhound
      - bloodhound.py

# BloodHound will not work unless you change the Neo4j password from
# the default value.
- name: Set the initial password for Neo4j
  block:
    # By default a very recent version of OpenJDK 17 is being used on
    # Kali Linux.  Neo4j <5 requires OpenJDK 11.
    #
    # TODO: This task can be removed once we upgrade to Neo4j version
    # 5, as discussed in #136.
    - name: Install OpenJDK 11
      ansible.builtin.include_role:
        name: openjdk

    - name: Start Neo4j
      ansible.builtin.command:
        cmd: /usr/bin/neo4j start
      changed_when: start_neo4j.rc == 0
      failed_when: start_neo4j.rc != 0
      register: start_neo4j

    - name: Set Neo4j password
      ansible.builtin.command:
        cmd: >
          /usr/share/neo4j/bin/neo4j-admin
          set-initial-password {{ password }}
      changed_when: set_initial_password.rc == 0
      failed_when: set_initial_password.rc != 0
      no_log: true
      register: set_initial_password

    - name: Stop Neo4j
      ansible.builtin.command:
        cmd: /usr/bin/neo4j stop
      changed_when: stop_neo4j.rc == 0
      failed_when: stop_neo4j.rc != 0
      register: stop_neo4j
