---
# cloud-init-main.service is not currently enabled on Kali.
- name: Enable cloud-init-main.service
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Enable cloud-init-main.service
      ansible.builtin.service:
        name: cloud-init-main.service
        enabled: true
