---
- name: Setup Wazuh agent
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install and configure Wazuh agent
      ansible.builtin.include_role:
        name: wazuh_agent
      vars:
        # The IP or hostname of the Wazuh manager
        wazuh_agent_manager: >-
          {{ lookup('amazon.aws.ssm_parameter', '/wazuh_agent/manager') }}
