---
- name: Install dependencies for aquatone
  ansible.builtin.package:
    name:
      - chromium

- name: Install aquatone
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    assessment_tool_archive_src: "https://github.com/michenriksen/\
    aquatone/releases/download/v1.7.0/aquatone_linux_amd64_1.7.0.zip"
    assessment_tool_install_dir: /tools/aquatone
