---
# Note that this playbook installs Burp Suite Pro for the VNC user,
# and therefore can only run _after_ the VNC user has been created.
- hosts: all
  name: Install assessment tools
  become: yes
  become_method: sudo
  vars:
    # The group that should own the tools installed to /target.  The
    # VNC user is in this group.
    group: kali-trusted
    vnc_username: "{{ lookup('aws_ssm', '/vnc/username') }}"
  roles:
    - role: assessment_tool
      vars:
        archive_src: https://github.com/3ndG4me/AutoBlue-MS17-010/tarball/master
        install_dir: /tools/AutoBlue-MS17-010
        pip_requirements_file: requirements.txt
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/C-Sto/BananaPhone/tarball/master
        install_dir: /tools/BananaPhone
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/ajpc500/BOFs/tarball/main
        install_dir: /tools/BOFs
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/mdsecactivebreach/CACTUSTORCH/\
        tarball/master"
        csharp: yes
        install_dir: /tools/CACTUSTORCH
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/Techno-Hwizrdry/checkpwnedemails/\
        tarball/master"
        install_dir: /tools/checkpwnedemails
        pip_packages:
          - requests
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/bovine/datapipe/tarball/master
        install_dir: /tools/datapipe
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/nccgroup/demiguise/tarball/master
        install_dir: /tools/demiguise
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/maurosoria/dirsearch/tarball/master
        install_dir: /tools/dirsearch
        pip_requirements_file: requirements.txt
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/sixdub/DomainTrustExplorer/\
        tarball/master"
        install_dir: /tools/DomainTrustExplorer
        pip_packages:
          - matplotlib
          - networkx
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/tyranid/DotNetToJScript/tarball/master
        csharp: yes
        install_dir: /tools/DotNetToJScript
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        # TODO: Switch to master branch after Forked branch is merged
        # See https://github.com/cisagov/kali-packer/issues/139
        archive_src: "https://github.com/tarrell13/Egress-Assess/\
        tarball/Forked"
        install_dir: /tools/Egress-Assess
        pip_requirements_file: requirements.txt
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/BC-SECURITY/Empire/tarball/master"
        csharp: yes
        install_dir: /tools/Empire
        pip_packages:
          - .
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/MacR6/ftpenum/tarball/master
        install_dir: /tools/ftpenum
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/GhostPack/Lockless/tarball/master
        csharp: yes
        install_dir: /tools/GhostPack/Lockless
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/GhostPack/Rubeus/tarball/master
        csharp: yes
        install_dir: /tools/GhostPack/Rubeus
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/GhostPack/Seatbelt/tarball/master
        csharp: yes
        install_dir: /tools/GhostPack/Seatbelt
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/GhostPack/SafetyKatz/tarball/master
        csharp: yes
        install_dir: /tools/GhostPack/SafetyKatz
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/GhostPack/SharpDPAPI/tarball/master
        csharp: yes
        install_dir: /tools/GhostPack/SharpDPAPI
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/GhostPack/SharpDump/tarball/master
        csharp: yes
        install_dir: /tools/GhostPack/SharpDump
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/GhostPack/SharpRoast/tarball/master
        csharp: yes
        install_dir: /tools/GhostPack/SharpRoast
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/GhostPack/SharpUp/tarball/master
        csharp: yes
        install_dir: /tools/GhostPack/SharpUp
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/GhostPack/SharpWMI/tarball/master
        csharp: yes
        install_dir: /tools/GhostPack/SharpWMI
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/ChrisTruncer/gnmap-parser/tarball/master
        install_dir: /tools/gnmap-parser
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/FortyNorthSecurity/Hasher/tarball/master
        install_dir: /tools/Hasher
        pip_packages:
          - .
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/HarmJ0y/ImpDump/tarball/master
        install_dir: /tools/ImpDump
        pip_packages:
          - impacket
          - pycrypto
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/eladshamir/Internal-Monologue/\
        tarball/master"
        csharp: yes
        install_dir: /tools/Internal-Monologue
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/HarmJ0y/KeeThief/tarball/master
        csharp: yes
        install_dir: /tools/KeeThief
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/xan7r/kerberoast/tarball/master
        install_dir: /tools/kerberoast
        pip_packages:
          - pyasn1
          - scapy
        powershell: yes
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/gentilkiwi/mimikatz/tarball/master
        install_dir: /tools/mimikatz
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/ChrisTruncer/mikto/tarball/master
        install_dir: /tools/mikto
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/xan7r/Misc/tarball/master
        install_dir: /tools/Misc
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/fox-it/mitm6/tarball/master
        install_dir: /tools/mitm6
        pip_packages:
          - .
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/vysecurity/morphHTA/tarball/master
        install_dir: /tools/morphHTA
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/worawit/MS17-010/tarball/master
        install_dir: /tools/MS17-010
        pip_packages:
          - impacket
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/noahpowers/nlzr/tarball/master
        install_dir: /tools/nlzr
        pip_packages:
          - requests
          - requests-toolbelt
          - Sublist3r
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/PowerShellEmpire/PowerTools/\
        tarball/master"
        install_dir: /tools/PowerTools
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/NetSPI/PowerUpSQL/tarball/master
        install_dir: /tools/PowerUpSQL
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/xorrior/RandomPS-Scripts/tarball/master
        install_dir: /tools/RandomPS-Scripts
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/resyncgg/ripgen/tarball/main
        install_dir: /tools/ripgen
        rust: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/danielmiessler/SecLists/tarball/master
        install_dir: /tools/SecLists
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/Arvanaghi/SessionGopher/tarball/master
        install_dir: /tools/SessionGopher
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/mubix/shellshocker-pocs/tarball/master
        install_dir: /tools/shellshocker-pocs
        pip_packages:
          - scapy
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/SimplySecurity/SimplyEmail/\
        tarball/master"
        install_dir: /tools/SimplyEmail
        # The misspelling here is intentional.  See
        # https://github.com/SimplySecurity/SimplyEmail/blob/master/setup/requirments.txt.
        pip_requirements_file: setup/requirments.txt
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/SimplySecurity/SimplyTemplate/\
        tarball/master"
        install_dir: /tools/SimplyTemplate
        pip_packages:
          - glob2
          - configparser
          - Pillow
          - pmw
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/sqlmapproject/sqlmap/\
        tarball/master"
        install_dir: /tools/sqlmap
        # This forces the creation of a Python 3 venv
        pip_packages:
          - pip
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/MacR6/sshenum/tarball/master
        install_dir: /tools/sshenum
        pip_packages:
          - paramiko
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/rasta-mouse/TikiTorch/tarball/master
        csharp: yes
        install_dir: /tools/TikiTorch
        unarchive_extra_opts:
          - --strip-components=1
    - role: assessment_tool
      vars:
        archive_src: https://github.com/tomnomnom/waybackurls/tarball/master
        go: yes
        install_dir: /tools/waybackurls
        unarchive_extra_opts:
          - --strip-components=1
    - role: burp_suite_pro
      vars:
        # The name of the AWS S3 bucket where third-party software is
        # located
        third_party_bucket_name: "{{ build_bucket }}"
        # License Burp Suite Pro for the VNC user
        users:
          - "{{ vnc_username }}"
    - role: metasploit
    - role: server_setup
    - role: visual_studio_code

  tasks:
    - name: Install system packages for tools where possible
      ansible.builtin.package:
        name:
          - assetfinder
          - cargo
          - cifs-utils
          - dnsutils
          - dos2unix
          - exploitdb
          - eyewitness
          - feroxbuster
          - firefox-developer-edition-en-us-kbx
          - flameshot
          - getallurls
          - gobuster
          - golang
          - jq
          - libreoffice
          - nfs-common
          - nikto
          - nmap
          - php
          - powersploit
          - proxychains
          - python3-shodan
          - python3-venv
          - screen
          - subfinder
          - sublist3r
          - terminator
          - testssl.sh
          - veil
          - vim
          - whois
          - wpscan

    # In order for the VNC user to make full use of Go, we need to add
    # $p/bin to the PATH for all paths p in $GOPATH.
    #
    # See #137 for more details.
    - name: Add GOPATH binary paths to PATH for VNC user
      ansible.builtin.blockinfile:
        # The jinja2 comment below changes the Jinja2 templating to
        # look for square braces instead of curly braces for comments;
        # otherwise, Jinja2 thinks the "{#" character combinations
        # below are for it and that causes an error.
        block: |
          #jinja2:comment_start_string:'[#' , comment_end_string:'#]'
          #####
          # Grab the Go environment variables
          #####
          eval "$(go env)"

          #####
          # Add $p/bin to the PATH for all paths p in $GOPATH.
          #####

          # Try to remove a :* substring from the end of GOPATH.  This
          # will tell us if GOPATH is a single path or a
          # colon-delimited list of paths.
          dummy=${GOPATH%%:*}
          if [ ${#GOPATH} -eq ${#dummy} ]
          then
              # We were _unable_ to remove a :* substring from the end
              # of GOPATH, so it must be the case that GOPATH contains
              # only a single path with no colon delimiter.
              PATH=$GOPATH/bin:$PATH
          else
              # We were _able_ to remove a :* substring from the end
              # of GOPATH, so it must be the case that GOPATH contains
              # multiple paths separated by colon delimiters.
              PATH=${GOPATH//://bin:}:$PATH
          fi
          unset dummy
          export PATH
        group: vnc
        mode: 0644
        owner: vnc
        path: /home/{{ vnc_username }}/.bashrc

    # The kaboxer group is created via the
    # firefox-developer-edition-en-us-kbx package, and the VNC user
    # must be a member of this group to run Firefox Developer Edition.
    - name: Add VNC user to kaboxer group
      ansible.builtin.user:
        append: yes
        groups:
          - kaboxer
        name: "{{ vnc_username }}"

    # Aquatone requires Google Chromium
    - name: Install Aquatone
      ansible.builtin.import_tasks: aquatone.yml

    - name: Install BloodHound
      ansible.builtin.import_tasks: bloodhound.yml
      vars:
        # The password for Neo4j
        password: "{{ lookup('aws_ssm', '/neo4j/password') }}"

    - name: Install Cobalt Strike
      ansible.builtin.import_tasks: cobalt_strike.yml

    - name: Install CrackMapExec
      ansible.builtin.import_tasks: crackmapexec.yml

    # dns-profile-randomizer lives in a private GitLab repository and
    # hence must be downloaded using a GitLab access token.
    - name: Install dns-profile-randomizer
      ansible.builtin.import_tasks: dns_profile_randomizer.yml

    - name: Install Donut
      ansible.builtin.import_tasks: donut.yml

    - name: Install EXCELntDonut
      ansible.builtin.import_tasks: excelntdonut.yml

    - name: Install PCredz
      ansible.builtin.import_tasks: pcredz.yml

    - name: Install Responder
      ansible.builtin.import_tasks: responder.yml

    - name: Install ScareCrow
      ansible.builtin.import_tasks: scarecrow.yml

    - name: Install SharpShooter
      ansible.builtin.import_tasks: sharpshooter.yml

    # ysoserial requires a Java implementation
    - name: Install ysoserial
      ansible.builtin.import_tasks: ysoserial.yml
