---
- hosts: all
  name: Install Bloodhound and Cobalt Strike
  become: yes
  become_method: sudo
  roles:
    - role: bloodhound
      vars:
        # The password for Neo4j
        password: "{{ lookup('aws_ssm', '/neo4j/password') }}"
    - role: cobalt_strike

- hosts: all
  name: Install other Kali tools
  become: yes
  become_method: sudo
  roles:
    - role: kali
      vars:
        # The GitLab PAT used to pull dns-profile-randomizer from a
        # private repository.
        gitlab_token: "{{ lookup('aws_ssm',
        '/gitlab/personal_authorization_token') }}"
        # The group that should own the tools installed to /target.
        # The VNC user is in this group.
        group: kali-trusted
