---
- hosts: aws
  name: AWS-specific roles
  become: yes
  become_method: sudo
  roles:
    - amazon_efs_utils
    - cloudwatch_agent
    # The instance types used for almost all the instances expose EBS
    # volumes as NVMe block devices, so that's why we need nvme here.
    - nvme
