---
- name: Setup base image
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    # The assessments folks specifically asked us _not_ to patch the
    # Kali instances while they are running.
    # - name: Install and configure automated security updates
    #   ansible.builtin.include_role:
    #     name: automated_security_updates
    - name: Install and configure login banner
      ansible.builtin.include_role:
        name: banner
    - name: Install and configure ClamAV
      ansible.builtin.include_role:
        name: clamav
    - name: Install and configure Docker
      ansible.builtin.include_role:
        name: docker
    - name: Install and configure htop
      ansible.builtin.include_role:
        name: htop
    - name: Configure JournalD to preserve logs across reboots
      ansible.builtin.include_role:
        name: persist_journald
    # Kali by default uses NetworkManager instead of systemd-networkd,
    # so it doesn't make sense to install systemd-resolved on this
    # platform.
    # - name: Install and configure systemd-resolved
    #   ansible.builtin.include_role:
    #     name: systemd_resolved
