---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - banner
    - clamav
    - dev_ssh_access
    - docker
    - htop
    - persist_journald
    - sshd_allow_rsa
