---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    # The assessments folks specifically asked us _not_ to patch the
    # Kali instances while they are running.
    # - automated_security_updates
    - banner
    - clamav
    - docker
    - htop
    - persist_journald
    - sshd_allow_rsa
