---
- name: Install C2 Tool Collection
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    archive_src: https://github.com/outflanknl/C2-Tool-Collection/tarball/main
    install_dir: /tools/C2-Tool-Collection
    unarchive_extra_opts:
      - --strip-components=1

- name: Build Beacon Object Files
  ansible.builtin.make:
    chdir: /tools/C2-Tool-Collection/BOF
