---
- name: Install C2 Tool Collection
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    assessment_tool_archive_src: https://github.com/outflanknl/C2-Tool-Collection/tarball/main
    assessment_tool_install_dir: /tools/C2-Tool-Collection
    assessment_tool_unarchive_extra_opts:
      - --strip-components=1

- name: Build Beacon Object Files
  community.general.make:
    chdir: /tools/C2-Tool-Collection/BOF
