---
# For some reason cloud-init-local, cloud-config, and cloud-final are
# not enabled in the base Kali AMI.  We need cloud-config anabled, and
# we may as well enable the others while we're at it.
- hosts: all
  name: Enable all cloud-init services
  become: yes
  become_method: sudo
  tasks:
    - name: Enable all cloud-init services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: yes
      loop:
        - cloud-init-local
        - cloud-init
        - cloud-config
        - cloud-final

    # The Kali base AMI we are using does not seem to have run this.
    # If we don't do it now then userdata, for instance, will be
    # ignored and not run when our AMI is started.
    - name: Run cloud-init clean --logs
      ansible.builtin.command:
        argv:
          - /usr/bin/cloud-init
          - clean
          - --logs
