---
- hosts: all
  name: Install Cobalt Strike
  become: yes
  become_method: sudo
  roles:
    - openjdk
    - role: cobalt_strike
      vars:
        bucket_name: "{{ build_bucket }}"
    - server_setup
  tasks:
    - name: Install Thunderbird mail client
      package:
        name: thunderbird
    - name: Install some tools manually
      block:
        - name: Create a directory for each tool that must be installed manually
          file:
            group: "{{ group }}"
            # Allow both root and the desired group to have full
            # permissions in these directories
            mode: 0775
            path: "{{ manually_installed_tools_base_dir }}/{{ item.dir_name }}"
            state: directory
          loop: "{{ manually_installed_tools }}"
          loop_control:
            label: "{{ item.dir_name }}"
        - name: Manually install each tool
          unarchive:
            dest: "{{ manually_installed_tools_base_dir }}/{{ item.dir_name }}"
            extra_opts:
              - "--strip-components=1"
            group: "{{ group }}"
            mode: 0644
            remote_src: yes
            src: "{{ item.repo }}"
          loop: "{{ manually_installed_tools }}"
          loop_control:
            label: "{{ item.repo }}"
      vars:
        # Group ownership for the tools that are installed directly to /tools
        group: wheel
        # Base directory where all manually-installed tools will be installed
        manually_installed_tools_base_dir: "/tools"
        # Tools to be manually installed
        manually_installed_tools:
          - dir_name: "CobaltStrike-Toolkit"
            repo: |
              https://github.com/killswitch-GUI/CobaltStrike-Toolkit/tarball/master
          - dir_name: "Malleable-C2-Profiles"
            repo: |
              https://github.com/rsmudge/Malleable-C2-Profiles/tarball/master
          - dir_name: "Malleable-C2-Randomizer"
            repo: |
              https://github.com/bluscreenofjeff/Malleable-C2-Randomizer/tarball/master
    - name: Install Mono for the manually installed packages that need it
      package:
        name:
          - mono-complete
