---
# The assessors like to use Thunderbird with Cobalt Strike
- name: Install Thunderbird mail client
  ansible.builtin.package:
    name: thunderbird

- name: Install Cobalt Strike
  ansible.builtin.include_role:
    name: cobalt_strike
  vars:
    cobalt_strike_bucket_name: "{{ build_bucket }}"

- name: Install some Cobalt Strike addons
  block:
    - name: Install CobaltStrike-Toolkit
      ansible.builtin.include_role:
        name: assessment_tool
      vars:
        assessment_tool_archive_src: "https://github.com/killswitch-GUI/\
        CobaltStrike-Toolkit/tarball/master"
        assessment_tool_install_dir: /tools/CobaltStrike-Toolkit
        assessment_tool_powershell: true
    - name: Install Malleable-C2-Profiles
      ansible.builtin.include_role:
        name: assessment_tool
      vars:
        assessment_tool_archive_src: "https://github.com/rsmudge/\
        Malleable-C2-Profiles/tarball/master"
        assessment_tool_install_dir: /tools/Malleable-C2-Profiles
    - name: Install Malleable-C2-Randomizer
      ansible.builtin.include_role:
        name: assessment_tool
      vars:
        assessment_tool_archive_src: "https://github.com/\
        bluscreenofjeff/Malleable-C2-Randomizer/tarball/master"
        assessment_tool_install_dir: /tools/Malleable-C2-Randomizer
