---
# The following CrackMapExec dependencies require the specified
# packages be installed:
# * gssapi requires the krb5-config executable from the libkrb5-dev
#   package
- name: Install CrackMapExec dependencies
  ansible.builtin.package:
    name:
      - libkrb5-dev

- name: Install CrackMapExec
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    assessment_tool_archive_src: >
      https://github.com/Porchetta-Industries/CrackMapExec/tarball/master
    # This is not a cargo project, although it requires a Rust
    # compiler.
    assessment_tool_cargo_build: no
    assessment_tool_install_dir: /tools/CrackMapExec
    assessment_tool_pip_packages:
      - .
    # Although this is a Python project, the dependency aardwolf
    # requires a Rust compiler to build its native code.
    assessment_tool_rust: yes
    assessment_tool_unarchive_extra_opts:
      - --strip-components=1
