---
# We have to grab the code, build the C code, and then we can build
# the Python extension
- name: Install Donut
  ansible.builtin.import_role:
    name: assessment_tool
  vars:
    archive_src: https://github.com/TheWover/donut/tarball/master
    install_dir: /tools/donut
    unarchive_extra_opts:
      - --strip-components=1

- name: Build Donut
  ansible.builtin.make:
    chdir: /tools/donut

- name: Create venv and build Donut Python extension
  ansible.builtin.import_role:
    name: assessment_tool
  vars:
    install_dir: /tools/donut
    pip_packages:
      - .
