---
# We have to grab the code, build the C code, and then we can build
# the Python extension
- name: Install Donut
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    assessment_tool_archive_src: https://github.com/TheWover/donut/tarball/master
    assessment_tool_install_dir: /tools/donut
    assessment_tool_unarchive_extra_opts:
      - --strip-components=1

- name: Build Donut
  community.general.make:
    chdir: /tools/donut

- name: Create venv and build Donut Python extension
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    assessment_tool_install_dir: /tools/donut
    assessment_tool_pip_packages:
      - .
