---
# The installation of PCredz is a little finicky.  First off, it
# requires that libpcap-dev be installed.  Second, Cython must be
# installed _before_ python-libpcap, so I have to set up the virtual
# env in two stages.
- name: Install libpcap-dev
  ansible.builtin.package:
    name:
      - libpcap-dev
- name: Create venv and install Cython
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    install_dir: /tools/PCredz
    pip_packages:
      - Cython
    unarchive_extra_opts:
      - --strip-components=1
- name: Install PCredz
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    archive_src: https://github.com/lgandx/PCredz/tarball/master
    install_dir: /tools/PCredz
    pip_packages:
      - python-libpcap
    unarchive_extra_opts:
      - --strip-components=1
