---
- name: Install pip3/python3 and remove pip2/python2
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    # If pip were to be installed first, then the OS _could_ pull
    # different Python packages than what would be installed via the
    # cisagov/ansible-role-python role; hence, the ordering below is
    # more controlled.
    - name: Install Python 3
      ansible.builtin.include_role:
        name: python
    - name: Install pip3
      ansible.builtin.include_role:
        name: pip
    - name: Uninstall Python 2
      ansible.builtin.include_role:
        name: remove_python2
