---
- src: https://github.com/cisagov/ansible-role-amazon-efs-utils
  name: amazon_efs_utils
- src: https://github.com/cisagov/ansible-role-amazon-ssm-agent
  name: amazon_ssm_agent
- src: https://github.com/cisagov/ansible-role-assessment-tool
  name: assessment_tool
# The assessments folks specifically asked us _not_ to patch the Kali
# instances while they are running.
# - src: https://github.com/cisagov/ansible-role-automated-security-updates
#   name: automated_security_updates
- src: https://github.com/cisagov/ansible-role-banner
  name: banner
- src: https://github.com/cisagov/ansible-role-burp-suite-pro
  name: burp_suite_pro
- src: https://github.com/cisagov/ansible-role-chrony-aws
  name: chrony_aws
- src: https://github.com/cisagov/ansible-role-clamav
  name: clamav
- src: https://github.com/cisagov/ansible-role-cloudwatch-agent
  name: cloudwatch_agent
- src: https://github.com/cisagov/ansible-role-cobalt-strike
  name: cobalt_strike
- src: https://github.com/cisagov/ansible-role-docker
  name: docker
- src: https://github.com/cisagov/ansible-role-htop
  name: htop
- src: https://github.com/cisagov/ansible-role-metasploit
  name: metasploit
- src: https://github.com/cisagov/ansible-role-nvme
  name: nvme
- src: https://github.com/cisagov/ansible-role-openjdk
  name: openjdk
  version: improvement/configure-alternatives-for-debian
- src: https://github.com/cisagov/ansible-role-persist-journald
  name: persist_journald
- src: https://github.com/cisagov/ansible-role-pip
  name: pip
- src: https://github.com/cisagov/ansible-role-python
  name: python
- src: https://github.com/cisagov/ansible-role-remove-python2
  name: remove_python2
- src: https://github.com/cisagov/ansible-role-server-setup
  name: server_setup
- src: https://github.com/cisagov/ansible-role-sshd-allow-rsa
  name: sshd_allow_rsa
- src: https://github.com/cisagov/ansible-role-ufw
  name: ufw
- src: https://github.com/cisagov/ansible-role-upgrade
  name: upgrade
- src: gantsign.visual-studio-code
  name: visual_studio_code
- src: https://github.com/cisagov/ansible-role-vnc-server
  name: vnc
- src: https://github.com/cisagov/ansible-role-xfce-cool
  name: xfce_cool
