---
# Responder requires the libncurses6 package in order to build the
# wheel for readline.
- name: Install Responder dependencies
  ansible.builtin.package:
    name:
      - libncurses6

- name: Install Responder
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    archive_src: https://github.com/lgandx/Responder/tarball/master
    install_dir: /tools/Responder
    pip_packages:
      - dnspython
      - impacket
      - ldap3
      - pyasn1
      - pycryptodome
      - pycryptodomex
      - readline
      - six
    unarchive_extra_opts:
      - --strip-components=1
