---
- name: Install Responder
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    assessment_tool_archive_src: https://github.com/lgandx/Responder/tarball/master
    assessment_tool_install_dir: /tools/Responder
    assessment_tool_pip_packages:
      - dnspython
      - impacket
      - ldap3
      - pyasn1
      - pycryptodome
      - pycryptodomex
      - six
    assessment_tool_unarchive_extra_opts:
      - --strip-components=1
