---
# The installation of SharpShooter is a little finicky.  The project
# is no longer supported, but it mixes spaces and tabs in its Python
# source code, so we need to run autopep8 on it.
- name: Install SharpShooter
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    assessment_tool_archive_src: "https://github.com/mdsecactivebreach/SharpShooter/\
    tarball/master"
    assessment_tool_csharp: true
    assessment_tool_install_dir: /tools/SharpShooter
    assessment_tool_pip_requirements_file: requirements.txt
    assessment_tool_python2: true
    assessment_tool_unarchive_extra_opts:
      - --strip-components=1

- name: Install python3-autopep8
  ansible.builtin.package:
    name:
      # This additional dependency is here because SharpShooter's
      # Python source code mixes spaces and tabs, so we need to run
      # autopep8 against it.  See cisagov/cool-system-internal#73 for
      # more details.
      - python3-autopep8

- name: Run autopep8 on the SharpShooter source code
  ansible.builtin.command:
    argv:
      - /usr/bin/autopep8
      - --recursive
      - --in-place
      - .
    chdir: /tools/SharpShooter
  changed_when: autopep8.rc == 0
  failed_when: autopep8.rc != 0
  register: autopep8
