---
- hosts: all
  name: Install ufw
  become: yes
  become_method: sudo
  roles:
    - ufw

- hosts: all
  name: Basic configuration for UFW
  become: yes
  become_method: sudo
  tasks:
    - name: Allow incoming traffic through specified TCP ports
      community.general.ufw:
        proto: tcp
        rule: allow
        to_port: "{{ item }}"
      loop:
        - "22"       # ssh for Guacamole server (internal to assessment env)
        - 5000:5999  # Additional listeners, if necessary (external)
        - "5901"     # vnc for Guacamole (internal to assessment env)
    - name: Deny incoming traffic to specified TCP ports
      # These rules may be manually modified by assessors as needed, but we
      # want to default to a minimal set of allowed ports.
      #
      # Note that these "deny" rules were explicitly requested in
      # cisagov/cool-system-internal#80.  For additional context, see:
      # https://github.com/cisagov/kali-packer/pull/92#discussion_r796234923
      community.general.ufw:
        proto: tcp
        rule: deny
        to_port: "{{ item }}"
      loop:
        - 8000:8999  # Additional listeners, if necessary (external)
