---
- hosts: all
  name: Upgrade base image
  become: yes
  become_method: sudo
  tasks:
    - name: Upgrade
      ansible.builtin.import_role:
        name: upgrade
    # The base AMI currently ships with a 6.0.0 kernel, which as
    # described in #131 has a bug that does not allow ext4 filesystems
    # to be resized; therefore, it makes sense to go ahead and boot
    # into the >=6.0.8 kernel installed in the previous upgrade step
    # since it does not have the bug.
    - name: Boot into the updated (>=6.0.8) kernel
      block:
        - name: Install kexec
          ansible.builtin.package:
            name:
              kexec-tools
        # Our base AMI still uses grub instead of systemd-boot, and
        # systemd kexec does not parse grub configs, so kexec cannot
        # function without first manually loading the updated kernel
        # into the current kernel.
        - name: Load the updated (>=6.0.8) kernel into the current kernel
          ansible.builtin.command:
            argv:
              - /sbin/kexec
              - --load
              - /boot/vmlinuz-6.0.0-kali6-cloud-amd64
              - --initrd=/boot/initrd.img-6.0.0-kali6-cloud-amd64
              - --reuse-cmdline
        - name: Boot into the updated (>=6.0.8) kernel
          ansible.builtin.command:
            cmd: /usr/bin/systemctl kexec
          # Give the system ten minutes to come back online
          async: 600
          # Do not poll, but immediately go on to the next task
          poll: 0
        - name: Wait for the system to come back online
          ansible.builtin.wait_for_connection:
            # Wait a minute before starting to poll
            delay: 60
            # Sleep for one minute between checks
            sleep: 60
            # Wait ten minutes for the connection to come back online.
            # This number should agree with the value of the async
            # attribute in the previous task.
            timeout: 600
    - name: Resize the root filesystem
      ansible.builtin.command:
        argv:
          - /usr/bin/growpart
          - /dev/nvme0n1
          - 1
