---
- hosts: all
  name: Install VNC
  become: yes
  become_method: sudo
  roles:
    - role: vnc
      vars:
        # The user information and ssh keys for the VNC user
        password: "{{ lookup('aws_ssm', '/vnc/password') }}"
        private_ssh_key: "{{ lookup('aws_ssm', '/vnc/ssh/rsa_private_key') }}"
        public_ssh_key: "{{ lookup('aws_ssm', '/vnc/ssh/rsa_public_key') }}"
        user_groups:
          # Note that this means that the aws.yml playbook _must_ run
          # before this one, so that the efs_users group has been
          # created.
          - efs_users
          - kali-trusted
        # Note that we use the same UID for the VNC and Samba guest
        # users on all instances.  This helos us avoid UID/GID
        # collisions with files written to the EFS share.
        user_uid: 2048
        username: "{{ lookup('aws_ssm', '/vnc/username') }}"
