---
# ysoserial requires a Java implementation
- name: Install OpenJDK
  ansible.builtin.include_role:
    name: openjdk

- name: Install ysoserial
  ansible.builtin.include_role:
    name: assessment_tool
  vars:
    archive_src: https://github.com/frohoff/ysoserial/tarball/master
    install_dir: /tools/ysoserial
    unarchive_extra_opts:
      - --strip-components=1
